# Generated by Django 4.2.11 on 2026-01-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=200)),
                ('example', models.TextField(blank=True)),
                ('level', models.CharField(blank=True, max_length=10)),
                ('topic', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
