# Generated by Django 6.0.1 on 2026-01-23 12:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='level',
        ),
        migrations.RemoveField(
            model_name='word',
            name='topic',
        ),
        migrations.AddField(
            model_name='word',
            name='last_reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='next_review',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='word',
            name='times_failed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='times_seen',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
